[package]
authors = ["yoshihiro <n.yoshihiro.jp@gmail.com>"]
edition = "2018"
name = "abc187"
version = "0.1.0"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
